language: php

php:
  - 7.3

services:
  - docker

before_install:
- docker pull uspdev/asedocker
- docker run -d -p 127.0.0.1:80:5000 uspdev/asedocker
- docker ps -a
#- docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test"

#script:
#  - vendor/bin/phpunit